# Generated by Django 3.0.2 on 2020-03-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drumbeatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instruments',
            new_name='Instrument',
        ),
    ]
