# Generated by Django 3.0.2 on 2020-03-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drumbeatapp', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
